[package]
name = "StackedStocks"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio", "time"] }
tokio = { version = "1.44.2", features = ["rt-multi-thread", "tokio-macros"] }
uuid = "1.16.0"
