services:
     redis:
        image: redis
        expose:
           - "6379"
        networks:
           - backend
        healthcheck:
           test: ["CMD", "redis-cli", "ping"]
           interval: 5s
           timeout: 2s
           retries: 5
     auth:
        build:
           context: .
           dockerfile: services/auth_service/Dockerfile.dev
        volumes:
           - .:/app
           - /app/target
        expose:
           - "4002"
        networks:
           - backend
        depends_on:
           redis:
              condition: service_healthy
     gateway:
        build:
           context: .
           dockerfile: services/gateway/Dockerfile.dev
        volumes:
           - .:/app
           - /app/target
        ports:
           - "4001:4001"
        networks:
           - backend

networks:
     backend:
        driver: bridge
