FROM rust:1.85

RUN cargo install watchexec-cli

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY shared/ shared/

COPY services/ services/

RUN cargo build -p gateway

WORKDIR /app/services/gateway

CMD ["watchexec", "-r", "--", "cargo", "run", "gateway"]
