{
 "title": "OpenTelemetry APM",
 "description": "A language-agnostic application performance management(APM) with OpenTelemetry, Grafana, and Prometheus.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(service_name)" } },
   { "name": "route", "label": "Route", "query": { "query": "label_values(http_route)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (request_counter_total{service_name=\"Gateway\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(traces_spanmetrics_latency_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", http_route=~\"$route\"}) by(service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (request_counter_total{service_name=\"Gateway\", status=~\"^2.*\"}) by(status)",
     "legendFormat": "Http Status 2XX"
    },
    {
     "expr": "sum(request_counter_total{service_name=\"Gateway\", status=~\"^3.*\"}) by(status) ",
     "legendFormat": "Http Status 3XX"
    },
    {
     "expr": "sum(request_counter_total{service_name=\"Gateway\", status=~\"^4.*\"}) by(status) ",
     "legendFormat": "Http Status 4XX"
    },
    {
     "expr": "sum(request_counter_total{service_name=\"Gateway\", status=~\"^5.*\"}) by(status) ",
     "legendFormat": "Http Status 5XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^2.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 2XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^3.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 3XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^4.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 4XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^5.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 5XX"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "description": "request amount distribution",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path) (request_counter_total{service_name=\"Gateway\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Loading Distribution",
   "type": "piechart",
   "description": "cumulative latency distribution",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path) (request_timer_seconds_sum{service_name=\"Gateway\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "gauge",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service=\"Gateway\"}[3m]) * 60)"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "gauge",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(request_counter_total{service_name=\"Gateway\", status=~\"^5.*\"}) / sum(request_counter_total{service_name=\"Gateway\"})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(path) (rate(request_counter_total{service_name=\"Gateway\"}[3m])) * 60",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PR95 Latency",
   "type": "timeseries",
   "description": "PR95 latency over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(request_timer_seconds_bucket{service_name=\"Gateway\"}[3m])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(path, status) (request_timer_seconds_sum{service_name=\"Gateway\"}) / sum by(path, status) (request_counter_total{service_name=\"Gateway\"}))",
     "legendFormat": "[{{status}}] {{path}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "description": "Details of each API",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(service_name, path, method) (rate(request_timer_seconds_count{service_name=\"Gateway\"}[3m])) * 60"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, service_name, method, path) (rate(request_timer_seconds_bucket{service_name=\"Gateway\"}[3m])))"
    },
    {
     "expr": "sum by(service_name, method, path) (request_timer_seconds_count{status!~\"2.*|3.*\"}) / sum by(service_name, method, path) (request_timer_seconds_count{service_name=\"Gateway\"})"
    }
   ]
  }
 ]
}