FROM rust:1.85

RUN cargo install watchexec-cli

WORKDIR /app

COPY Cargo.toml Cargo.lock ./

COPY shared/ shared/

COPY services/ services/

RUN cargo build -p auth_service

WORKDIR /app/services/user_service

CMD ["watchexec", "-r", "--", "cargo", "run", "user_service"]
